SimpleBlog.WebUI/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBlog.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

SimpleBlog.WebUI/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SimpleBlog.DAL.Context;
using SimpleBlog.DAL.DataService;
using SimpleBlog.DAL.Identity;
using SimpleBlog.DAL.Object_Model;
using SimpleBlog.DAL.ViewModel;

namespace SimpleBlog.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserController : Controller
    {
        private UnitOfWork _unitOfWork;

        public UserController()
        {
            _unitOfWork = new UnitOfWork(ApplicationContext.Create());
        }

        public ActionResult List()
        {
            var users = _unitOfWork.DataContext.Users.ToList();
            if (users.Any())
            {
                return View(Mapper.Map<IEnumerable<ApplicationUser>, IEnumerable<UserViewModel>>(users));
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var user = _unitOfWork.DataContext.Users.Find(id);
            if (user != null)
            {
                return View(user);
            }
            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                var passwordHash = new PasswordHasher();
                if (!string.IsNullOrWhiteSpace(model.NewPassword))
                {
                    model.PasswordHash = passwordHash.HashPassword(model.NewPassword);
                }
                _unitOfWork.DataContext.Entry(model).State = EntityState.Modified;
                _unitOfWork.Save();
                return RedirectToAction("LogOff", "Account", new { @area = "" });
            }
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Remove(string id)
        {
            if (_unitOfWork.DataContext.Users.Count() > 1)
            {
                var user = _unitOfWork.DataContext.Users.Find(id);
                if (user != null)
                {
                    return View(user);
                }
                ModelState.AddModelError("OnlyOneUser", "В системе есть только один пользователь. Удаление невозможно");
                return RedirectToAction("List");
            }
            return RedirectToAction("List");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Remove(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.DataContext.Entry(model).State = EntityState.Deleted;
                _unitOfWork.Save();
                return RedirectToAction("List");
            }
            return RedirectToAction("List");
        }


        [HttpGet]
        public ActionResult Add()
        {
            return View(new UserViewModel());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(_unitOfWork.DataContext));

                var user = new ApplicationUser()
                {
                    UserName = model.UserName,
                    Email = model.Email,
                    EmailConfirmed = true,
                    FullName = model.FullName
                };

                var roleManager = new RoleManager<ApplicationRole>(new RoleStore<ApplicationRole>(_unitOfWork.DataContext));

                var role = await roleManager.FindByNameAsync("roleAdmin");
                var result = await manager.CreateAsync(user, model.PasswordHash);
                if (result.Succeeded && role != null)
                {
                    manager.AddToRole(user.Id, role.Name);
                }
                else
                {
                    throw new NullReferenceException();
                }

                return RedirectToAction("List");
            }
            return HttpNotFound();
        }
    }
}

SimpleBlog.WebUI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using SimpleBlog.DAL.Context;
using SimpleBlog.DAL.DataService;
using SimpleBlog.DAL.Object_Model;
using SimpleBlog.DAL.ViewModel;
using SimpleBlog.WebUI.Utils;
using WebGrease.Css.Extensions;

namespace SimpleBlog.WebUI.Controllers
{
    [RoutePrefix("blog")]
    public class BlogController : Controller
    {
        private int _pageSize = 5;
        private UnitOfWork _unitOfWork;
        
        public BlogController()
        {
            _unitOfWork = new UnitOfWork(ApplicationContext.Create());
            _pageSize = int.Parse(AppSettingsStore.GetPostsPerPage().Value);
        }

        [Route("page/{page}")]
        public async Task<ActionResult> Posts(int page = 1)
        {
            ViewBag.Title = "Блог";
            ViewBag.Description = "Блог";

            var posts = await _unitOfWork.DataContext.Posts.Where(x => x.IsPublished).ToListAsync();
            var model = new PostsListViewModel()
            {
                PagingInfoViewModel = new PagingInfoViewModel()
                {
                    CurrentPage = page,
                    PostsPerPage = _pageSize,
                    TotalPosts = posts.Count
                },
                PostViewModels = posts.Select(Mapper.Map<Post, PostViewModel>).OrderByDescending(p => p.PublishDate).Skip((page - 1) * _pageSize).Take(_pageSize).ToList()
            };
            return View(model);
        }

        [Route("{url?}")]
        public async Task<ActionResult> Details(string url = null)
        {
            ViewBag.Title = "Блог";
            ViewBag.Description = "Блог";

            if (!string.IsNullOrWhiteSpace(url))
            {
                var post = await _unitOfWork.DataContext.Posts.FirstOrDefaultAsync(x => x.UrlSlug == url);
                PostViewModel model = Mapper.Map<Post, PostViewModel>(post);
                return View(model);
            }
            return HttpNotFound();
        }

        [Route("search/{query?}")]
        [HttpPost]
        public async Task<ActionResult> Search(string query)
        {
            ViewBag.Title = "Поиск";
            ViewBag.Description = "Поиск";
            ViewBag.Query = query;
            if (!string.IsNullOrWhiteSpace(query))
            {
                var posts =
                    await
                        _unitOfWork.DataContext.Posts.Where(
                            post =>
                                post.Title.Contains(query) || post.ShortDescription.Contains(query) ||
                                post.Description.Contains(query)).ToListAsync();
                var model = Mapper.Map<IEnumerable<Post>, IEnumerable<PostViewModel>>(posts);
                return View(model);
            }
            return HttpNotFound();
        }

        [Route("tag/{tag?}")]
        public async Task<ActionResult> SearchByTag(string tag)
        {
            return HttpNotFound();
        }
    }
}

SimpleBlog.WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using SimpleBlog.WebUI.Utils

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="icon" href="~/Content/Images/favicon-cloud.ico">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<!--Main Menu-->
    @if (User.Identity.IsAuthenticated)
    {
        <nav class="navbar navbar-default navbar-inverse" style="border: 2px solid black;">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><i class="fa fa-cog" style="color: white"></i></a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index", "Dashboard", new {area = "Admin"})"><i class="fa fa-home"></i> В админку</a></li>
                        <li><a href="@Url.Action("Posts", "Post", new { area = "Admin" })"><i class="fa fa-sticky-note"></i> Записи</a></li>
                        <li><a href="@Url.Action("List", "User", new { area = "Admin" })"><i class="fa fa-user"></i> Пользователи</a></li>
                        <li><a href="@Url.Action("List", "Setting", new { area = "Admin" })"><i class="fa fa-cog"></i> Настройки</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><i class="fa fa-user"></i> Вы вошли как @User.Identity.Name</a></li>
                        <li><a href="@Url.Action("LogOff", "Account")"><i class="fa fa-times-circle-o"></i> Выйти</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    }
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-cloud"></span><span style="margin-left: 10px;"> Dmitry Osin</span></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav  navbar-right">
                    <li>@Html.ActionLink("Блог", "Posts", "Blog", new {page = 1}, null)</li>
                    <li><a href="@Url.Action("AboutMe", "Home")">Обо мне</a></li>
                    <li><a href="@Url.Action("Contacts", "Home")">Контакты</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="hidden-sm hidden-md"><a href="#">Мои работы</a></li>
                    <li class="hidden-sm hidden-md"><a href="#">Сертификаты</a></li>
                    <li class="hidden-sm hidden-md hidden-lg"><a href="#">Навыки</a></li>
                    <li class="hidden-sm hidden-md hidden-lg"><a href="#">Сотрудничество</a></li>
                    <li class="hidden-sm hidden-md hidden-lg"><a href="#">Правообладателям</a></li>
                    <li class="hidden-sm hidden-md hidden-lg"><a href="#">Копипастерам</a></li>

                    <li class="dropdown hidden-xs">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger"></span><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="hidden-lg"><a href="#">Мои работы</a></li>
                            <li class="hidden-lg"><a href="#">Сертификаты</a></li>
                            <li class=""><a href="#">Навыки</a></li>
                            <li class=""><a href="#">Сотрудничество</a></li>
                            <li class=""><a href="#">Правообладателям</a></li>
                            <li class=""><a href="#">Копипастерам</a></li>
                        </ul>

                    </li>
                    <li class="dropdown hidden-xs">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-search"></span><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                @using (Html.BeginForm("Search", "Blog", FormMethod.Post, new { style = "width: 300px; padding: 20px;" }))
                                {
                                    <div class="form-group">
                                        <label for="search-field">Что ищем?</label>
                                        <input type="search" name="query" class="form-control"
                                               id="search-field" placeholder="поисковый запрос" />
                                    </div>

                                    <button type="submit" class="btn btn-default">Искать</button>
                                }
                            </li>
                        </ul>

                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <!--Main Menu-->

    <div id="header" class="container-fluid">
        <br />
        <a href="#">
            <img id="header-image" src="../../Content/Images/logo.jpg" alt="logo" class="img-rounded img-circle img-thumbnail shadow img-responsive center-block">
        </a>
        <h1 id="header-text" align="center">@AppSettingsStore.GetBlogName().Value</h1>
    </div>


    <!--Main Content-->

    <div class="container-fluid">
        @RenderBody()
    </div>
    <!--Main Content End-->
    <!--Footer Begin-->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row" style="margin-top: 20px;">
                <div class="col-md-4 col-md-offset-1 col-lg-offset-2">
                    <span class="text-uppercase">
                        <span class="glyphicon glyphicon-copyright-mark" style="margin-right: 20px;"></span>Dmitry Osin, 2016
                    </span>
                </div>

                <div class="col-md-6 hidden-xs hidden-sm">
                    <span class="text-uppercase">
                        <span class="glyphicon glyphicon-flash" style="margin-right: 20px; color: yellow;"></span>Заряжено мощью <a href="http://asp.net/" style="color: rgb(115, 187, 189)">ASP.NET MVC5</a> и <a href="http://getbootstrap.com/" style="color: darksalmon">Bootstrap</a>
                    </span>
                </div>

            </div>
        </div>
    </footer>
    <!--Footer End-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/prism")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>